name: delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.70.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_hooks: ^0.18.5+1
  pointer_interceptor: ^0.9.3+3
  geodesy: ^0.10.2
  firebase_ui_auth: ^1.13.1
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  firebase_dynamic_links: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Bicycle.png
    - assets/images/Car.png
    - assets/images/Motorcycle.png

fonts:
  family: Montserrat
  fonts:
    asset: fonts/Montserrat-Regular.ttf