name: delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.70.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_hooks: ^0.18.5+1
  pointer_interceptor: ^0.9.3+3
  geodesy: ^0.10.2
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.1
  firebase_database: ^10.5.1
  flutter_launcher_icons: ^0.13.1
  dropdown_button2: ^2.3.9
  image_picker: ^0.8.4+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Bicycle.png
    - assets/images/Car.png
    - assets/images/Motorcycle.png
    - assets/images/authlogo.jpeg
    - assets/images/user.png

fonts:
  family: Montserrat
  fonts:
    asset: fonts/Montserrat-Regular.ttf
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpeg"