// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfCaXn4TtlejGSGHakK_oM6XUusMhmrQ',
    appId: '1:248452815694:web:b8ccff68ffea0e39691c1f',
    messagingSenderId: '248452815694',
    projectId: 'flutter-delivery-efa31',
    authDomain: 'flutter-delivery-efa31.firebaseapp.com',
    storageBucket: 'flutter-delivery-efa31.appspot.com',
    measurementId: 'G-LKGWJCCHHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK33vED3MDQ0nCUyVl1whAC-nZ-q7tB_A',
    appId: '1:248452815694:android:188518e5e5a5a79e691c1f',
    messagingSenderId: '248452815694',
    projectId: 'flutter-delivery-efa31',
    storageBucket: 'flutter-delivery-efa31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCksLX6aTSzgalK-nUfR7vDqDfcVLS4864',
    appId: '1:248452815694:ios:54c54ce608799f98691c1f',
    messagingSenderId: '248452815694',
    projectId: 'flutter-delivery-efa31',
    storageBucket: 'flutter-delivery-efa31.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCksLX6aTSzgalK-nUfR7vDqDfcVLS4864',
    appId: '1:248452815694:ios:7b6f654c8a2b0946691c1f',
    messagingSenderId: '248452815694',
    projectId: 'flutter-delivery-efa31',
    storageBucket: 'flutter-delivery-efa31.appspot.com',
    iosBundleId: 'com.example.delivery.RunnerTests',
  );
}
